<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>7b9d0ef4-5752-43b7-ade9-901c2bab0407</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\UltraSinger.Contracts\UltraSinger.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    </ItemGroup>
</Project>
